### ISSUE TITLE
 03 April 2020 - Team 100 - The Aries - Peer to Peer Review #6

### ISSUE THREAD

**Issue by kevcap** [jstloyal/Laptop-Directory#2]
# Hey Tayo @jstloyal  ,  your work looks as awesome as your presentation💥 Congratulations for the great work, Our team really liked it and I think that it's awesome! 😎 👍

**Team comments:**

1- At least one H1 tag;
2- convert divs into articles;
3- correct search.html;
4- improve your titles;

Keep up that good work!

🙋 Anytime, anything, just reach me by slack, [instagram](instagram.com/kevinnnnmn/), [LinKevin](linkedin.com/in/kevinnn) or 
[![Twitter Follow](https://img.shields.io/twitter/follow/kevinfrontend?label=Follow%20Kevin%20on%20Twitter&style=social)](https://twitter.com/kevinfrontend)

Keep Healthy 🏊 and Keep Happy 😄!

**Comment by jstloyal** [comment]
Thank you!!
